apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: hello-app-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app-api
  template:
    metadata:
      labels:
        app: hello-app-api
    spec:
      containers:
      - name: hello-app-api
        image: longthanhle1122/hello-app-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
